name: portfolio
description: "my pixel art portfolio"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: 0.20.2

  flutter_svg: ^2.2.0
  blur: ^4.0.0
  percent_indicator: ^4.2.5
  modal_bottom_sheet: ^3.0.0
  toastification: ^2.3.0
  top_modal_sheet: ^2.1.0
  easy_url_launcher: ^0.0.7
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  lottie: ^3.0.0
  dio: ^5.4.0
  auto_size_text: ^3.0.0
  google_fonts: ^6.3.0
  font_awesome_flutter: ^10.9.1
  flutter_layout_grid: ^2.0.8
  flutter_staggered_grid_view: ^0.7.0
  get: ^4.7.2
  supabase_flutter: ^2.9.1
  web_splash: ^1.0.4
  flutter_dotenv: ^6.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0

dependency_overrides:
  intl: ^0.19.0

flutter_launcher_icons:
  android: "logo"
  ios: true
  image_path: "assets/logo/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/logo/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logo/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo/logo.png"


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/logo/